### ISSUE TITLE
eth0: Lost carrier

### ISSUE THREAD

**Issue by marcinporebski** [Azure/aks-engine#4341]
We're having networking issues when using this version on Azure. We run multiple environments with dozens of VMs but only the ones using this version show us similar symptoms of frequent "Lost carrier".

Version: 2020.09.14 / aks-engine-ubuntu-1804-202007

When we see in the image syslog we see that when compiling the image or testing it you also got this in logs, so this is probably isse within the image:

```
Sep 14 23:08:37 pkrvmimxmt6a7t5 systemd-networkd[798]: eth0: Gained carrier
Sep 14 23:08:37 pkrvmimxmt6a7t5 systemd-networkd[798]: eth0: Lost carrier
Sep 14 23:08:37 pkrvmimxmt6a7t5 systemd-networkd[798]: eth0: Gained carrier
Sep 14 23:12:54 pkrvmimxmt6a7t5 systemd-networkd[798]: vethb4facb2: Gained carrier
Sep 14 23:12:54 pkrvmimxmt6a7t5 systemd-networkd[798]: docker0: Gained carrier
Sep 14 23:12:55 pkrvmimxmt6a7t5 systemd-networkd[798]: vethb4facb2: Lost carrier
Sep 14 23:12:56 pkrvmimxmt6a7t5 systemd-networkd[798]: docker0: Lost carrier
Sep 14 23:13:00 pkrvmimxmt6a7t5 systemd-networkd[798]: veth0682687: Gained carrier
Sep 14 23:13:00 pkrvmimxmt6a7t5 systemd-networkd[798]: docker0: Gained carrier
Sep 14 23:13:02 pkrvmimxmt6a7t5 systemd-networkd[798]: veth0682687: Lost carrier
Sep 14 23:13:03 pkrvmimxmt6a7t5 systemd-networkd[798]: docker0: Lost carrier
Sep 14 23:21:34 pkrvmimxmt6a7t5 systemd-networkd[798]: vethe28eb3a: Gained carrier
Sep 14 23:21:34 pkrvmimxmt6a7t5 systemd-networkd[798]: docker0: Gained carrier
Sep 14 23:21:35 pkrvmimxmt6a7t5 systemd-networkd[798]: vethe28eb3a: Lost carrier
Sep 14 23:21:36 pkrvmimxmt6a7t5 systemd-networkd[798]: vethce787a6: Gained carrier
Sep 14 23:21:37 pkrvmimxmt6a7t5 systemd-networkd[798]: vethce787a6: Lost carrier
Sep 14 23:21:37 pkrvmimxmt6a7t5 systemd-networkd[798]: docker0: Lost carrier
Sep 14 23:22:03 pkrvmimxmt6a7t5 systemd-networkd[798]: veth61fa694: Gained carrier
Sep 14 23:22:03 pkrvmimxmt6a7t5 systemd-networkd[798]: docker0: Gained carrier
Sep 14 23:22:04 pkrvmimxmt6a7t5 systemd-networkd[798]: veth61fa694: Lost carrier
Sep 14 23:22:04 pkrvmimxmt6a7t5 systemd-networkd[798]: docker0: Lost carrier
Sep 14 23:22:05 pkrvmimxmt6a7t5 systemd-networkd[798]: vethc3724e7: Gained carrier
Sep 14 23:22:05 pkrvmimxmt6a7t5 systemd-networkd[798]: docker0: Gained carrier
Sep 14 23:22:06 pkrvmimxmt6a7t5 systemd-networkd[798]: vethc3724e7: Lost carrier
Sep 14 23:22:06 pkrvmimxmt6a7t5 systemd-networkd[798]: docker0: Lost carrier
Sep 14 23:22:30 pkrvmimxmt6a7t5 systemd-networkd[798]: veth0aaee97: Gained carrier
```

**Comment by marcinporebski** [comment]
On our machines in syslog we get this very frequent:

```
Mar 18 18:35:04 [the-name-of-the-vm] systemd-networkd[975]: eth0: Gained carrier
Mar 18 18:35:04 [the-name-of-the-vm] systemd-networkd[975]: enP1s1: Gained carrier
Mar 18 18:35:04 [the-name-of-the-vm] systemd-networkd[975]: enP1s1: Lost carrier
Mar 18 18:35:04 [the-name-of-the-vm] systemd-networkd[975]: eth0: Lost carrier
Mar 18 18:35:04 [the-name-of-the-vm] systemd-networkd[975]: enP1s1: Gained carrier
Mar 18 18:35:04 [the-name-of-the-vm] systemd-networkd[975]: eth0: Gained carrier
Mar 18 18:35:43 [the-name-of-the-vm] systemd-networkd[975]: cbr0: Gained carrier
Mar 18 18:35:43 [the-name-of-the-vm] systemd-networkd[975]: vethb2aa6e21: Gained carrier
Mar 18 18:35:43 [the-name-of-the-vm] systemd-networkd[975]: vethdd944935: Gained carrier
Mar 18 18:35:43 [the-name-of-the-vm] systemd-networkd[975]: vethc68b6ced: Gained carrier
Mar 18 18:35:44 [the-name-of-the-vm] systemd-networkd[975]: vethd41a59f7: Gained carrier
Mar 18 18:35:44 [the-name-of-the-vm] systemd-networkd[975]: veth2b2db244: Gained carrier
Mar 18 18:35:44 [the-name-of-the-vm] systemd-networkd[975]: veth7e3a5c35: Gained carrier
Mar 18 18:36:05 [the-name-of-the-vm] systemd-networkd[975]: veth157a4013: Gained carrier
Mar 18 18:36:05 [the-name-of-the-vm] systemd-networkd[975]: veth307ee20e: Gained carrier
Mar 18 18:37:01 [the-name-of-the-vm] systemd-networkd[975]: eth0: Lost carrier
Mar 18 18:37:03 [the-name-of-the-vm] systemd-networkd[975]: eth0: Gained carrier
Mar 18 18:38:57 [the-name-of-the-vm] systemd-networkd[975]: veth5f36a92d: Gained carrier
Mar 18 18:39:26 [the-name-of-the-vm] systemd-networkd[975]: eth0: Lost carrier
Mar 18 18:39:28 [the-name-of-the-vm] systemd-networkd[975]: eth0: Gained carrier
Mar 18 18:42:06 [the-name-of-the-vm] systemd-networkd[975]: eth0: Lost carrier
Mar 18 18:42:08 [the-name-of-the-vm] systemd-networkd[975]: eth0: Gained carrier
Mar 18 18:42:16 [the-name-of-the-vm] systemd-networkd[975]: veth7e3a5c35: Lost carrier
Mar 18 18:42:18 [the-name-of-the-vm] systemd-networkd[975]: veth2b2db244: Lost carrier
Mar 18 18:42:18 [the-name-of-the-vm] systemd-networkd[975]: veth157a4013: Lost carrier
Mar 18 18:44:09 [the-name-of-the-vm] systemd-networkd[975]: veth48cc410e: Gained carrier
Mar 18 18:44:09 [the-name-of-the-vm] systemd-networkd[975]: veth841ecc27: Gained carrier
Mar 18 18:46:06 [the-name-of-the-vm] systemd-networkd[975]: veth9187d9dc: Gained carrier
Mar 18 18:46:21 [the-name-of-the-vm] systemd-networkd[975]: vethdd944935: Lost carrier
Mar 18 18:47:06 [the-name-of-the-vm] systemd-networkd[975]: vethe4546ead: Gained carrier
Mar 18 18:47:20 [the-name-of-the-vm] systemd-networkd[975]: vethb2aa6e21: Lost carrier
Mar 18 18:47:21 [the-name-of-the-vm] systemd-networkd[975]: veth307ee20e: Lost carrier
Mar 18 18:47:57 [the-name-of-the-vm] systemd-networkd[975]: vetha562273b: Gained carrier
Mar 18 18:48:07 [the-name-of-the-vm] systemd-networkd[975]: veth09ad4da1: Gained carrier
Mar 18 18:54:09 [the-name-of-the-vm] systemd-networkd[975]: eth0: Lost carrier
Mar 18 18:54:11 [the-name-of-the-vm] systemd-networkd[975]: eth0: Gained carrier
Mar 18 18:54:32 [the-name-of-the-vm] systemd-networkd[975]: eth0: Lost carrier
Mar 18 18:54:34 [the-name-of-the-vm] systemd-networkd[975]: eth0: Gained carrier
Mar 18 18:55:16 [the-name-of-the-vm] systemd-networkd[975]: vetha562273b: Lost carrier
Mar 18 18:55:19 [the-name-of-the-vm] systemd-networkd[975]: veth078f77cf: Gained carrier
Mar 18 18:55:30 [the-name-of-the-vm] systemd-networkd[975]: veth09ad4da1: Lost carrier
Mar 18 18:55:30 [the-name-of-the-vm] systemd-networkd[975]: vethe4546ead: Lost carrier
```

**Comment by seguler** [comment]
There is a known issue within Azure Network where the dhcp lease is lost whenever a disk attach/detach happens on some VM fleets. There is a fix rolling out at the moment to regions. I'll check to see when Azure Status update will be published for this.

**Comment by cheenamalhotra** [comment]
Hi @seguler 

Does this issue also apply to AKS Windows pods?

**Comment by Psybax** [comment]
@seguler Hi any update to this issue?

**Comment by Psybax** [comment]
We have the same issue, the pod log is listed as below.
![image](https://user-images.githubusercontent.com/77722804/127427144-a8507275-3ad8-403e-a618-5072729dba5d.png)
Also we have a SqlException caused by this.
```
Microsoft.Data.SqlClient.SqlException (0x80131904): Execution Timeout Expired.  The timeout period elapsed prior to completion of the operation or the server is not responding.
 ---> System.ComponentModel.Win32Exception (258): Unknown error 258
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__203_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(DbContext _, Boolean result, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToArrayAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at IdentityServer4.EntityFramework.Stores.ResourceStore.FindApiResourcesByScopeAsync(IEnumerable`1 scopeNames)
   at IdentityServer4.Stores.IResourceStoreExtensions.FindResourcesByScopeAsync(IResourceStore store, IEnumerable`1 scopeNames)
   at IdentityServer4.Validation.ScopeValidator.AreScopesValidAsync(IEnumerable`1 requestedScopes, Boolean filterIdentityScopes)
   at IdentityServer4.Validation.TokenRequestValidator.ValidateRequestedScopesAsync(NameValueCollection parameters, Boolean ignoreImplicitIdentityScopes, Boolean ignoreImplicitOfflineAccess)
   at IdentityServer4.Validation.TokenRequestValidator.ValidateClientCredentialsRequestAsync(NameValueCollection parameters)
   at IdentityServer4.Validation.TokenRequestValidator.RunValidationAsync(Func`2 validationFunc, NameValueCollection parameters)
   at IdentityServer4.Validation.TokenRequestValidator.ValidateRequestAsync(NameValueCollection parameters, ClientSecretValidationResult clientValidationResult)
   at IdentityServer4.Endpoints.TokenEndpoint.ProcessTokenRequestAsync(HttpContext context)
   at IdentityServer4.Endpoints.TokenEndpoint.ProcessAsync(HttpContext context)
   at IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events)
ClientConnectionId:efe767e8-218c-4d51-83fb-f056458c5873
Error Number:-2,State:0,Class:11
ClientConnectionId before routing:a6ad0d59-0da9-4e7f-b1e2-38bf66b7dc35
Routing Destination:d8f85b48b22e.HS2.tr3529.northeurope1-a.worker.database.windows.net,11001
```

**Comment by Will-Bill** [comment]
This is happening daily for us - Linux App Service - Azure SQL Database:

"System.ComponentModel.Win32Exception (258): Unknown error 258"

Worse when traffic on site is higher, it seems. We have multiple websites running the same code, but the busiest one goes down more often. This might be anecdotal and not to do with load, but just giving an observation.

**Comment by matiasjuliobello** [comment]
Same here. 

- Linux container
- Net Core 3.1
- Connecting to a VM with SQL Server 2012

**Comment by seguler** [comment]
Apologies for the late response here. This issue was resolved promptly last year (late March, early April).

If you are observing that you lose DHCP lease or the NIC gets re-plumbed during a disk attach, please raise a support ticket.

**Comment by bridgetkromhout** [comment]
As stated in https://github.com/Azure/aks-engine/issues/4341#issuecomment-1072661715 we believe this issue to be resolved. That being said, AKS Engine is also deprecated, so please ensure you move to AKS or CAPZ; thanks.

**Comment by andrehaupt** [comment]
We observed this issue in March 2021, but it seems to have returned again.

We experienced the issue on AKSUbuntu-1804containerd-2021.08.07  and upgraded to AKSUbuntu-1804containerd-2022.03.23 nodes, but the issue remains.

~~~
# cat /var/log/syslog | grep 'carrier'
Apr  9 11:47:22 aks-workerpool-60475773-vmss00012R systemd-networkd[862]: veth88257c9e: Lost carrier
Apr  9 11:47:22 aks-workerpool-60475773-vmss00012R systemd-networkd[862]: vethd2d77919: Lost carrier
Apr  9 11:47:23 aks-workerpool-60475773-vmss00012R systemd-networkd[862]: vethf2096f11: Lost carrier
Apr  9 11:47:23 aks-workerpool-60475773-vmss00012R systemd-networkd[862]: vethc76087a1: Lost carrier
Apr  9 11:47:23 aks-workerpool-60475773-vmss00012R systemd-networkd[862]: vethe8343ebc: Lost carrier
Apr  9 11:47:23 aks-workerpool-60475773-vmss00012R systemd-networkd[862]: veth6ea6b7ab: Lost carrier
Apr  9 11:47:23 aks-workerpool-60475773-vmss00012R systemd-networkd[862]: veth677474f5: Lost carrier
Apr  9 11:47:23 aks-workerpool-60475773-vmss00012R systemd-networkd[862]: veth50e71787: Lost carrier
Apr  9 11:47:23 aks-workerpool-60475773-vmss00012R systemd-networkd[862]: veth26b404f7: Lost carrier
Apr  9 11:47:23 aks-workerpool-60475773-vmss00012R systemd-networkd[862]: veth19cad643: Lost carrier
Apr  9 11:47:52 aks-workerpool-60475773-vmss00012R systemd-networkd[862]: vetha9edce19: Lost carrier
Apr  9 12:41:10 aks-workerpool-60475773-vmss00012R systemd-networkd[862]: veth3ce19b3f: Gained carrier
Apr  9 12:45:05 aks-workerpool-60475773-vmss00012R systemd-networkd[862]: veth1cbbddc6: Lost carrier
Apr  9 12:45:13 aks-workerpool-60475773-vmss00012R systemd-networkd[862]: veth7eb8f0e1: Gained carrier
Apr  9 12:45:13 aks-workerpool-60475773-vmss00012R systemd-networkd[862]: veth2785e3a2: Gained carrier
Apr  9 12:45:14 aks-workerpool-60475773-vmss00012R systemd-networkd[862]: vethd10b7d73: Gained carrier
Apr  9 12:45:14 aks-workerpool-60475773-vmss00012R systemd-networkd[862]: veth481448aa: Gained carrier
Apr  9 12:45:14 aks-workerpool-60475773-vmss00012R systemd-networkd[862]: veth8b926f44: Gained carrier
Apr  9 12:45:14 aks-workerpool-60475773-vmss00012R systemd-networkd[862]: veth8718fd86: Gained carrier
Apr  9 12:45:14 aks-workerpool-60475773-vmss00012R systemd-networkd[862]: veth94aec698: Gained carrier
Apr  9 12:45:15 aks-workerpool-60475773-vmss00012R systemd-networkd[862]: vethe5fb4393: Gained carrier
Apr  9 12:45:15 aks-workerpool-60475773-vmss00012R systemd-networkd[862]: veth9fb7a52b: Gained carrier
Apr  9 12:45:16 aks-workerpool-60475773-vmss00012R systemd-networkd[862]: veth12703ae8: Gained carrier
Apr  9 12:45:16 aks-workerpool-60475773-vmss00012R systemd-networkd[862]: veth372f0e09: Gained carrier
~~~
